export const researchTools = [
  {
    id: "google-scholar",
    name: "Google Scholar",
    icon: "🎓",
    description: "Search academic papers and journals.",
    url: "https://scholar.google.com",
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    icon: "🧠",
    description: "Find scientific articles with AI.",
    url: "https://www.semanticscholar.org",
  },
  {
    id: "connected-papers",
    name: "Connected Papers",
    icon: "🌐",
    description: "Visualize paper citations and connections.",
    url: "https://www.connectedpapers.com",
  },
  {
    id: "research-rabbit",
    name: "ResearchRabbit",
    icon: "🐇",
    description: "AI assistant for literature review.",
    url: "https://www.researchrabbit.ai",
  },
  {
    id: "elicit",
    name: "Elicit",
    icon: "💡",
    description: "Discover and summarize research papers.",
    url: "https://elicit.com",
  },
  {
    id: "consensus",
    name: "Consensus",
    icon: "⚖️",
    description: "Get AI answers backed by scientific evidence.",
    url: "https://consensus.app",
  },
  {
    id: "scite",
    name: "Scite",
    icon: "🔬",
    description: "Analyze citation quality of research papers.",
    url: "https://scite.ai",
  },
  {
    id: "zotero",
    name: "Zotero",
    icon: "📂",
    description: "Find and organize academic references.",
    url: "https://www.zotero.org",
  },
  {
    id: "mendeley",
    name: "Mendeley",
    icon: "📚",
    description: "Reference manager for researchers.",
    url: "https://www.mendeley.com",
  },
  {
    id: "mybib",
    name: "MyBib",
    icon: "🏷️",
    description: "Generate citations in any style.",
    url: "https://www.mybib.com",
  },
  {
    id: "citation-machine",
    name: "Citation Machine",
    icon: "⚙️",
    description: "Create citations and bibliographies.",
    url: "https://www.citationmachine.net",
  },
  {
    id: "scribbr-citation-generator",
    name: "Scribbr Citation Generator",
    icon: "✒️",
    description: "Generate references in APA, MLA, and more.",
    url: "https://www.scribbr.com/citation/generator",
  },
  {
    id: "quillbot",
    name: "QuillBot",
    icon: "🪶",
    description: "Paraphrase and improve academic writing.",
    url: "https://quillbot.com",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    icon: "✍️",
    description: "Check grammar and writing quality.",
    url: "https://www.grammarly.com",
  },
  {
    id: "gptzero",
    name: "GPTZero",
    icon: "🛡️",
    description: "Detect AI-generated text.",
    url: "https://gptzero.me",
  },
  {
    id: "perplexity-ai",
    name: "Perplexity AI",
    icon: "🔮",
    description: "Research and write with AI.",
    url: "https://www.perplexity.ai",
  },
  {
    id: "core",
    name: "CORE",
    icon: "🏛️",
    description: "Access millions of academic papers.",
    url: "https://core.ac.uk",
  },
  {
    id: "openalex",
    name: "OpenAlex",
    icon: "📖",
    description: "Find open-access research papers.",
    url: "https://openalex.org",
  },
  {
    id: "base",
    name: "BASE",
    icon: "🔎",
    description: "Academic search engine.",
    url: "https://www.base-search.net",
  },
  {
    id: "doaj",
    name: "DOAJ",
    icon: "📓",
    description: "Search free scientific papers.",
    url: "https://doaj.org",
  },
];